version: "3"
networks:
  annotatorweb:
    external: false

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: annotator-frontend-client-dev
    ports:
      - "60143:60143"
    networks:
      - annotatorweb