version: "3"
networks:
  annotatorweb:
    external: false

services:
  frontend:
    image: annotator-frontend-client
    ports:
      - "60143:60143"
    volumes:
      - "./:/workspace"
    networks:
      - annotatorweb