version: "3"
networks:
  annotatorweb:
    external: false

services:
  development:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "60142:60142"
    networks:
      - annotatorweb